---
- name: Include docker role 
  include_role:
    name: geerlingguy.docker

- name: remove old files from remote host
  tags:
    - build-image
  file:
    path: '/home/{{ nginx_user }}/nginx-jsonrpc-lb'
    state: absent

- name: Copy files to remote host
  tags:
    - build-image
  copy:
    src: docker
    dest: '/home/{{nginx_user}}'

- name: Stop container
  docker_container:
    image: ewasm/nginx-jsonrpc-lb
    name: nginx-jsonrpc-lb
    state: absent
    force_kill: yes

- name: delete old container
  tags:
    - build-image
  docker_container:
    image: ewasm/nginx-jsonrpc-lb
    name: nginx-jsonrpc-lb
    state: absent
    force_kill: yes

- name: Build Docker image
  tags:
    - build-image
  docker_image:
    name: ewasm/nginx-jsonrpc-lb
    path: '/home/{{nginx_user}}/docker'
    state: present
    force: yes

- name: Delete previous keys
  tags:
    - update-keys
  file:
    state: absent
    path: /home/{{nginx_user}}/keys

- name: Copy DH parameters to server
  tags:
    - update-keys
  copy:
    src: keys
    dest: /home/{{nginx_user}}

- name: Start container
  docker_container:
    name: nginx-jsonrpc-lb
    image: ewasm/nginx-jsonrpc-lb
    state: started
    network_mode: host
    volumes:
      - '/home/{{nginx_user}}/keys/proxy_server.key:/etc/nginx/ssl_certs/proxy_server.key'
      - '/home/{{nginx_user}}/keys/proxy_server.crt:/etc/nginx/ssl_certs/proxy_server.crt'
      - '/home/{{nginx_user}}/keys/dhparam.pem:/etc/ssl/dhparam.pem'
